name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  build-and-test:
    name: Lint and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm test -- --run

      - name: Performance tests
        run: CI_PERF_THRESHOLD_MS=1500 npm run test:performance

      - name: Bias tests
        run: CI_BIAS_TOL=0.08 npm run test:bias